version: 2.1

jobs:
  build:
    docker:
      - image: node:17
    steps:
      - checkout
      - run: npm install -g esw
      - run: npm run lint
  test:
    docker:
      - image: node:17
    steps:
      - checkout
      - run: npm install -g jest
      - run: npm run test
  analyze:
    docker:
      - image: node:17
    steps:
      - checkout
      - run: npm audit

workflows:
  node-workflow:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analyze:
          requires:
            - "test"
